// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvlzmbamsqzqqbhdrqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bHptYmFtc3F6cXFiaGRycXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NDYyNjMsImV4cCI6MjA3NTMyMjI2M30.TqoptjaKfEx-Uu9EY7uPUo7QEAyqTGsP5-wXwwoZvMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});